***Python Problems***

**P1**

In [1]:
import math

def is_prime(n):
    if n == 2: return True
    if n == 1 or n == 0 or n % 2 == 0: return False
    
    for i in range(3, int(math.sqrt(n))+1, 2):
        if n % i == 0:
            return False
    return True

print(is_prime(21))

False


**P2**

In [2]:
def sort_words(text_path):
    all_words = []
    
    fd = open(text_path, 'r')
    line = fd.readline()
    while line:
        line = line.strip()
        if line == '':
            line = fd.readline()
            continue            
        
        for character in [',', '.', ':', ';']:
            line = line.replace(character, '')
        
        words = line.split(' ')        
        all_words += words
        
        line = fd.readline()
    
    return sorted(all_words)

print(sort_words('Latin-Lipsum.txt'))

['Deleniti', 'Eripuit', 'Est', 'Id', 'Ius', 'Nam', 'Quem', 'Qui', 'Sit', 'Te', 'Te', 'Vim', 'Vim', 'Vis', 'ad', 'ad', 'adipisci', 'adolescens', 'alienum', 'aliquid', 'an', 'an', 'an', 'appareat', 'assentior', 'assentior', 'at', 'at', 'at', 'audiam', 'brute', 'complectitur', 'concludaturque', 'congue', 'consectetuer', 'consequat', 'constituto', 'corrumpit', 'cu', 'cu', 'cu', 'cum', 'decore', 'disputando', 'dolore', 'duo', 'ea', 'ea', 'ea', 'eloquentiam', 'error', 'erroribus', 'est', 'est', 'eu', 'eu', 'euismod', 'eum', 'ex', 'ex', 'ex', 'ex', 'facete', 'fugit', 'gloriatur', 'has', 'his', 'id', 'instructior', 'iriure', 'labore', 'labores', 'laoreet', 'libris', 'lucilius', 'mea', 'mea', 'mea', 'mea', 'mea', 'mei', 'mei', 'melius', 'molestie', 'molestie', 'mollis', 'nam', 'ne', 'ne', 'nominati', 'nominavi', 'nominavi', 'nostro', 'nostro', 'nostrum', 'nusquam', 'nusquam', 'omittantur', 'omnium', 'patrioque', 'per', 'per', 'pertinacia', 'ponderum', 'possit', 'principes', 'pro', 'propriae', '

**P3**

In [3]:
from typing import List

def mat_mul(M: List[List[float]], v:List[float]) -> list:
    Mv = []
    for line in M:
        dot_product = 0
        for col_M, col_v in zip(line, v):
            dot_product += col_M*col_v    
        Mv.append(dot_product)
    
    return Mv

M = [[1, 2, 3, 4], [11, 12, 13, 14], [21, 22, 23, 24]]
v = [2, -5, 7, -10]
print(mat_mul(M, v))

[-27, -87, -147]


***Numpy Problems***

In [4]:
import numpy as np

**P1**

In [5]:
u = np.array(v)
N = np.array([np.array(l) for l in M])
print(N)
print(u)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]
[  2  -5   7 -10]


In [6]:
print(N[:2, -2:])
print(u[-2:])

[[ 3  4]
 [13 14]]
[  7 -10]


**P2**

In [7]:
n = 3
R1 = np.random.rand(3)
R2 = np.random.rand(3)
print(R1, R2)

[0.83977629 0.13741505 0.2876332 ] [0.26765013 0.1066061  0.24756161]


a) Compare sum of Vectors

In [8]:
R1 if np.sum(R1) >= np.sum(R2) else R2

array([0.83977629, 0.13741505, 0.2876332 ])

b) Sum and Product of Vectors

In [9]:
print(R1 + R2)

[1.10742643 0.24402116 0.5351948 ]


In [10]:
print(R1*R2)

[0.22476624 0.01464928 0.07120694]


In [11]:
print(np.outer(R1, R2))

[[0.22476624 0.08952528 0.20789637]
 [0.03677916 0.01464928 0.03401869]
 [0.07698506 0.03066345 0.07120694]]


c) Square Root of Vector

In [12]:
print(np.sqrt(R1))

[0.91639309 0.37069536 0.53631446]


**P3**

In [13]:
B = np.random.rand(5,5)
print(B)

[[0.83035461 0.26679882 0.94960108 0.31542819 0.86307315]
 [0.91097813 0.15861392 0.01504202 0.30919711 0.93727652]
 [0.49165335 0.79396902 0.14894773 0.66093534 0.36711227]
 [0.10028935 0.8624243  0.46869311 0.11129286 0.36835609]
 [0.54980947 0.49522292 0.24526859 0.02872221 0.02346581]]


a) Transpose

In [14]:
print(B.T)

[[0.83035461 0.91097813 0.49165335 0.10028935 0.54980947]
 [0.26679882 0.15861392 0.79396902 0.8624243  0.49522292]
 [0.94960108 0.01504202 0.14894773 0.46869311 0.24526859]
 [0.31542819 0.30919711 0.66093534 0.11129286 0.02872221]
 [0.86307315 0.93727652 0.36711227 0.36835609 0.02346581]]


b) Inverse and Determinant

In [15]:
print("Inverse:")
print(np.linalg.inv(B))
print("\n Determinant:")
print(np.linalg.det(B))

Inverse:
[[ 0.04305648  0.28957445 -0.07693215 -0.85652237  1.49902089]
 [-0.63439304  0.15760352  0.03678309  1.01825787  0.47833454]
 [ 1.13289051 -0.9770612  -0.06580597 -0.10177306 -0.01465779]
 [ 0.54906921 -0.75263267  1.83922686 -1.13952905 -1.01902512]
 [-0.13380419  1.02276617 -0.53713559  1.03772282 -1.20150845]]

 Determinant:
0.2424173980105172


***P3***

In [16]:
t = np.random.rand(5)
print(t)

[0.28317577 0.28520554 0.31156976 0.16706626 0.01931169]


In [17]:
print(np.matmul(B, t))

[0.67646059 0.37764794 0.52958584 0.44610517 0.37860299]
